### ISSUE TITLE
Parameters, data format?

### ISSUE THREAD

**Issue by pedrocolon93** [crawles/automl_service#1]
Is there any documentation on the data format or the parameters that you take in?

**Comment by crawles** [comment]
```
pipeline_id: 1
extract_features:
  column_id: example_id
  impute_function: tsfresh.utilities.dataframe_functions.impute
  default_fc_parameters: MinimalFCParameters()
model_training:
  model_args:
  model: sklearn.ensemble.RandomForestClassifier
```

The training specific parameters are specific to tsfresh, tpot, and sklearn. 

* [extract_features](http://tsfresh.readthedocs.io/en/latest/api/tsfresh.feature_extraction.html#module-tsfresh.feature_extraction.extraction)
* model - any sklearn-learn compatible classifier
* model_args - arguments for associated sklearn classifier

For the data format, you have to use the same format as shown in the data folder. Check out the appendix of the Jupyter [Notebook](https://github.com/crawles/automl_service/blob/master/modelling_and_usage.ipynb) to see how I generated the data.
